function energy = calculateEnergy(sij, s, n, i, j)
    % Calculate the energy contribution from a spin at position (i, j)

    % Calculate energy contributions from neighboring spins using Kronecker delta function
    energy = kroneckerDelta(sij - s(pbc(i + 1, n), j)) + ...
        kroneckerDelta(sij - s(i, pbc(j + 1, n))) + ...
        kroneckerDelta(sij - s(pbc(i - 1, n), j)) + ...
        kroneckerDelta(sij - s(i, pbc(j - 1, n))) + ...
        kroneckerDelta(sij - s(pbc(i + 1, n), pbc(j + 1, n))) + ...
        kroneckerDelta(sij - s(pbc(i - 1, n), pbc(j + 1, n))) + ...
        kroneckerDelta(sij - s(pbc(i + 1, n), pbc(j - 1, n))) + ...
        kroneckerDelta(sij - s(pbc(i - 1, n), pbc(j - 1, n)));

end
